using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace UClient
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class UApi
    {
        /// <summary>
        /// Deletes saved credentials for all payment provider bots
        /// </summary>
        public class DeleteSavedCredentials : Function<Ok>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "deleteSavedCredentials";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }
            

        }

        /// <summary>
        /// Deletes saved credentials for all payment provider bots
        /// </summary>
        public static Task<Ok> DeleteSavedCredentialsAsync(
            this Client client)
        {
            return client.ExecuteAsync(new DeleteSavedCredentials
            {
                
            });
        }
    }
}
