using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace UClient
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class UApi
    {
        /// <summary>
        /// Uses an invite link to add the current user to the chat if possible
        /// </summary>
        public class JoinChatByInviteLink : Function<Chat>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "joinChatByInviteLink";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }
            
/// <summary>
/// Invite link to import; must have URL "t.me", "telegram.me", or "telegram.dog" and query beginning with "/joinchat/" or "/+"
/// </summary>
[JsonConverter(typeof(Converter))]
[JsonProperty("invite_link")]
public string InviteLink { get; set; }


        }

        /// <summary>
        /// Uses an invite link to add the current user to the chat if possible
        /// </summary>
        public static Task<Chat> JoinChatByInviteLinkAsync(
            this Client client, string inviteLink = default)
        {
            return client.ExecuteAsync(new JoinChatByInviteLink
            {
                InviteLink = inviteLink
            });
        }
    }
}
