using System;
using Newtonsoft.Json;

namespace UClient
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class UApi
    {
        /// <summary>
        /// Contains memory statistics
        /// </summary>
        public partial class MemoryStatistics : Object
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "memoryStatistics";

            /// <summary>
            /// Extra data attached to the object
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

/// <summary>
/// Memory statistics in an unspecified human-readable format
/// </summary>
[JsonConverter(typeof(Converter))]
[JsonProperty("statistics")]
public string Statistics { get; set; }


        }
    }
}
